version: '3.7'
services:
  auth.mysql:
    container_name: auth.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks: 
      - dehia

  auth.php:
    container_name: auth.php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    user: ${LOCAL_USER}
    networks: 
      - dehia

  auth.nginx:
    container_name: auth.nginx
    image: nginx:1.15.3-alpine
    restart: on-failure
    depends_on:
      - auth.php
    networks: 
      - dehia

  auth.adminer:
    container_name: auth.adminer
    image: adminer
    restart: on-failure
    networks: 
      - dehia

networks:
  dehia:
    external: true