version: '3.3'
services:
 auth.php:
   volumes:
     - './app:/usr/src/app'

 auth.nginx:
   volumes:
     - './app/public/:/usr/src/app'
     - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
   ports:
     - '${NGINX_PORT}:80'

 auth.adminer:
   ports:
     - '${ADMINER_PORT}:8080'