version: '3.3'
services:
  auth.mysql:
    container_name: auth.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - auth.mysql

  auth.php:
    container_name: auth.php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    environment: 
      WAIT_HOSTS: auth.mysql:3306
      WAIT_SLEEP_INTERVAL: 10
      WAIT_BEFORE_HOSTS: 10
      WAIT_TIMEOUT: 350
    user: ${LOCAL_USER}
    depends_on: 
      - auth.mysql
    expose: 
      - 9000
    networks: 
      backend:
        aliases:
          - auth.php

  auth.nginx:
    container_name: auth.nginx
    image: nginx:1.17-alpine
    restart: on-failure
    depends_on:
      - auth.php
    networks:
      backend:
      dehia:
        aliases:
          - auth.nginx
      

  auth.adminer:
    container_name: auth.adminer
    depends_on: 
      - auth.mysql
    image: adminer:4.8.0
    restart: on-failure
    networks: 
      - backend

networks:
  dehia:
    external: true
  backend:
    external: false