version: '3.3'
services:
  auth.mysql:
    container_name: auth.mysql
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      backend:
        aliases:
          - auth.mysql

  auth.app:
    container_name: auth.app
    image: mokocchi/dehia-auth:latest
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    restart: on-failure
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      SITE_URL: ${SITE_URL}
      JWT_KEY: ${JWT_KEY}
      WAIT_HOSTS: ${DATABASE_HOST}:3306
      WAIT_SLEEP_INTERVAL: 10
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 350
    depends_on: 
      - ${DATABASE_HOST}
    expose:
      - 80
    networks: 
      backend:
      dehia:
        aliases:
          - auth.app

networks:
  dehia:
    external: true
  backend:
    external: false