nelmio_api_doc:
    documentation:
        info:
            title: DEHIA Auth
            description: Servicio de autenticación de DEHIA
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/(doc|doc.json)$)
