security:
    encoders:
        App\Entity\User:
            algorithm: sha512

    providers:
        api_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email

    firewalls:
        oauth_token:
            pattern: ^/api/oauth/v2/token
            security: false
            stateless: true

        validate_token:
            pattern: ^/api/validate
            stateless: true
            anonymous: false
            provider: api_user_provider
            fos_oauth: true